<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\HexServer.Core\HexServer.Core.csproj" />
    <ProjectReference Include="..\HexServer.Protocol\HexServer.Protocol.csproj" />
    <ProjectReference Include="..\HexServer.Game\HexServer.Game.csproj" />
    <ProjectReference Include="..\HexServer.Contracts\HexServer.Contracts.csproj" />
  </ItemGroup>
</Project>
